version: '3.3'

services:
  accounting-db:
    image: postgres:latest
    container_name: accounting-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSQORD: postgres
      POSTGRES_DB: accounting
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - accounting-data:/var/lib/postgresql/data

  accounting-backend:
    image: node:16
    container_name: accounting-backend
    working_dir: /app
    command: bash -c "npm run start:dev"
    environment:
      - PORT=3000
    ports:
      - "4300:3000"
    depends_on:
      - accounting-db
    volumes:
      - .:/app

volumes:
  accounting-data:
    driver: local

